macOS build: libxslt provided by macOS is *broken*, we need to replace it by homebrew version
When using the default libxslt provided by macOS, we get a compilation error which shows that it is actually broken:

The compilation emits this command line:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ \
    -Isrcml/src/libsrcml -Isrcml/src/libsrcml/. -Isrcml/src/parser/. -Isrcml/src/parser/SYSTEM \
    -Isrcml/build/parser \
    -isystem /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/libxml2 \       # incorrect path !!!
    -isystem /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include \               # incorrect path !!!
    -isystem srcml/build/_deps/antlrsrc-src/lib/cpp -O3 -DNDEBUG -std=gnu++17 -arch arm64 \
    -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk \                            # this include C standard lib before the C++ standard lib
    -fPIC -Wall -Wextra -pedantic -MD -MT src/libsrcml/CMakeFiles/libsrcml.dir/relaxngTransformation.cpp.o \
    -MF src/libsrcml/CMakeFiles/libsrcml.dir/relaxngTransformation.cpp.o.d \
    -o src/libsrcml/CMakeFiles/libsrcml.dir/relaxngTransformation.cpp.o \
    -c srcml/src/libsrcml/relaxngTransformation.cpp

It refers two path from an older macOS sdk, and it include the C standard lib before C++ standard lib headers
This leads to an error like this:

    [1/18] Building CXX object src/libsrcml/CMakeFiles/libsrcml.dir/language_extension_registry.cpp.o
    FAILED: src/libsrcml/CMakeFiles/libsrcml.dir/language_extension_registry.cpp.o
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -Isrcml/src/libsrcml -Isrcml/src/libsrcml/. -Isrcml/src/parser/. -Isrcml/src/parser/SYSTEM -Isrcml/build/parser -isystem /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/libxml2 -isystem /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include -isystem srcml/build/_deps/antlrsrc-src/lib/cpp -O3 -DNDEBUG -std=gnu++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -fPIC -Wall -Wextra -pedantic -MD -MT src/libsrcml/CMakeFiles/libsrcml.dir/language_extension_registry.cpp.o -MF src/libsrcml/CMakeFiles/libsrcml.dir/language_extension_registry.cpp.o.d -o src/libsrcml/CMakeFiles/libsrcml.dir/language_extension_registry.cpp.o -c srcml/src/libsrcml/language_extension_registry.cpp
    In file included from srcml/src/libsrcml/language_extension_registry.cpp:10:
    In file included from srcml/src/libsrcml/language_extension_registry.hpp:13:
    In file included from srcml/src/parser/./Language.hpp:14:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstdio:104:5:
    error: <cstdio> tried including <stdio.h> but didn't find libc++'s <stdio.h> header.
    This usually means that your header search paths are not configured properly.
    The header search paths should contain the C++ Standard Library headers before
    any C Standard Library, and you are probably using compiler flags that make that